/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mne.advertmanager.parsergen;

import com.mne.advertmanager.parsergen.model.Project;
import com.mne.advertmanager.util.JSoupTransport;
import java.io.File;
import javax.swing.JFileChooser;
import org.jsoup.Connection;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

/**
 *
 * @author Nina Eidelshtein and Misha Lebedev
 */
public class NewProjectDialog extends javax.swing.JDialog {

    private boolean isBaseUrlComplete = false;
    private boolean isUserNameComplete = false;
    private boolean isUserFieldComplete = false;
    private boolean isPasswordComplete = false;
    private boolean isPasswordFieldComplete = false;
    private boolean isHomeFolderComplete = false;
    private boolean isTestabale = isBaseUrlComplete & isUserNameComplete & isUserFieldComplete & isPasswordComplete & isPasswordFieldComplete;
    private boolean isInputComplete = isTestabale & isHomeFolderComplete;
    private Project curProject;

    public NewProjectDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        curProject = new Project();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMethod = new javax.swing.JLabel();
        cmbMethod = new javax.swing.JComboBox();
        btnTestConnection = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        lblHomeFolder = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblUserField = new javax.swing.JLabel();
        txtUserField = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblPasswordField = new javax.swing.JLabel();
        txtPasswordField = new javax.swing.JTextField();
        txtBaseUrl = new javax.swing.JTextField();
        lblBaseUrl = new javax.swing.JLabel();
        btnSelectHome = new javax.swing.JButton();
        lblSelector = new javax.swing.JLabel();
        txtSelector = new javax.swing.JTextField();
        lblCookie = new javax.swing.JLabel();
        txtCookie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLoginFormURL = new javax.swing.JFormattedTextField();
        lblLogout = new javax.swing.JLabel();
        txtLogout = new javax.swing.JTextField();

        setTitle("New project");
        setLocationByPlatform(true);
        setModal(true);
        setName("new");
        setResizable(false);

        lblMethod.setLabelFor(cmbMethod);
        lblMethod.setText("Method");

        cmbMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "get", "post" }));

        btnTestConnection.setText("TestConnection");
        btnTestConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTestConnection(evt);
            }
        });

        lblStatus.setText("Status");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreate(evt);
            }
        });

        lblHomeFolder.setToolTipText("select home folder");
        lblHomeFolder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onHomeFolderChange(evt);
            }
        });

        lblUser.setText("User Name");

        txtUserName.setText("vasya");
        txtUserName.setToolTipText("enter user name");
        txtUserName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onUserNameChange(evt);
            }
        });

        lblPassword.setText("Password");

        lblUserField.setText("User field name");

        txtUserField.setText("j_username");
        txtUserField.setToolTipText("enter username field name");
        txtUserField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onUserFieldNameChange(evt);
            }
        });

        txtPassword.setText("vasya");
        txtPassword.setToolTipText("enter password");
        txtPassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onPasswordChange(evt);
            }
        });

        lblPasswordField.setText("Password field name");

        txtPasswordField.setText("j_password");
        txtPasswordField.setToolTipText("enter password field name");
        txtPasswordField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onPasswordFieldChange(evt);
            }
        });

        txtBaseUrl.setText("http://localhost:8080/AdvertManager");
        txtBaseUrl.setToolTipText("enter base url");
        txtBaseUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseUrlActionPerformed(evt);
            }
        });
        txtBaseUrl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onBaseUrlChange(evt);
            }
        });

        lblBaseUrl.setLabelFor(txtBaseUrl);
        lblBaseUrl.setText("Base Url");

        btnSelectHome.setLabel("Select Home ");
        btnSelectHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelect(evt);
            }
        });

        lblSelector.setLabelFor(txtSelector);
        lblSelector.setText("Target Selector");

        txtSelector.setText("html > body div[id=content]");

        lblCookie.setText("SessionID CookieName");

        txtCookie.setText("JSESSIONID");

        jLabel1.setText("Login Form URL");

        txtLoginFormURL.setText("j_spring_security_check");

        lblLogout.setText("Logout URL");

        txtLogout.setText("j_spring_security_logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCookie)
                        .addGap(28, 28, 28)
                        .addComponent(txtCookie))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserField)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserField)
                            .addComponent(txtUserName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectHome)
                            .addComponent(lblBaseUrl)
                            .addComponent(lblMethod)
                            .addComponent(btnTestConnection)
                            .addComponent(lblPasswordField)
                            .addComponent(lblPassword)
                            .addComponent(jLabel1)
                            .addComponent(lblLogout))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHomeFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(txtPasswordField)
                            .addComponent(txtBaseUrl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLoginFormURL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSelector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLogout)))
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSelectHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHomeFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMethod)
                            .addComponent(cmbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelector)
                            .addComponent(txtSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBaseUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBaseUrl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoginFormURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogout)
                            .addComponent(txtLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCookie)
                            .addComponent(txtCookie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUser)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserField)
                            .addComponent(txtUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPasswordField)
                            .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTestConnection)
                            .addComponent(btnCreate))
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus)
                        .addContainerGap())))
        );

        jLabel5.getAccessibleContext().setAccessibleName("statusMessage");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onTestConnection(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTestConnection

        curProject.setBaseURL(txtBaseUrl.getText());
        curProject.setUserField(txtUserField.getText());
        curProject.setUsername(txtUserName.getText());
        curProject.setPasswordField(txtPasswordField.getText());
        curProject.setPassword(new String(txtPassword.getPassword()));
        curProject.setMethod(cmbMethod.getSelectedItem().toString());
        curProject.setSelector(txtSelector.getText());
        curProject.setCookieName(txtCookie.getText());
        curProject.setLoginFormUrl(txtLoginFormURL.getText());
        curProject.setLogoutUrl(txtLogout.getText());

        String status = validateSetupData(curProject);

        lblStatus.setText(status);
    }//GEN-LAST:event_onTestConnection

    private String validateSetupData(Project proj) {
        Document doc = null;
        Connection con = null;

        try {
            con = JSoupTransport.login(proj);
            if (con == null) {
                return "Status:Failure.Failed to login";
            }

            doc = JSoupTransport.retrieveDocument(con, proj.getBaseURL(),proj.getMethod());

            if (doc == null) {
                return "Status:Failure.Cannot retrieved document from url:"+proj.getBaseURL();
            }


            Element targetElem = doc.select(proj.getSelector()).first();
            if (targetElem != null) {
                return "Status:Success";
            } else {
                return "Status:Failure.Error in URL , form , cookie or credentials data";
            }
        } catch (Exception e) {
            return "Status:Failure.Exception:" + e.getClass().getSimpleName() + ".Message:" + e.getMessage();
        } finally {
            JSoupTransport.logout(con, proj);
        }
    }

    private void onCreate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreate
        System.out.println(curProject.toString());
        setVisible(false);
    }//GEN-LAST:event_onCreate

    private void onSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSelect
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int status = fc.showOpenDialog(this);
        File homeFolder = fc.getSelectedFile();
        lblHomeFolder.setText(homeFolder.getAbsolutePath());

    }//GEN-LAST:event_onSelect

    private void onBaseUrlChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onBaseUrlChange

        isBaseUrlComplete = txtBaseUrl.getText().length() > 0;
        setButtonsState();

    }//GEN-LAST:event_onBaseUrlChange

    private void onUserNameChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onUserNameChange

        isUserNameComplete = txtUserName.getText().length() > 0;
        setButtonsState();

    }//GEN-LAST:event_onUserNameChange

    private void onUserFieldNameChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onUserFieldNameChange
        isUserFieldComplete = txtUserField.getText().length() > 0;
        setButtonsState();

    }//GEN-LAST:event_onUserFieldNameChange

    private void onPasswordChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onPasswordChange
        isPasswordComplete = txtPassword.getPassword().length > 0;
        setButtonsState();
    }//GEN-LAST:event_onPasswordChange

    private void onPasswordFieldChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onPasswordFieldChange
        isPasswordFieldComplete = txtPasswordField.getText().length() > 0;
        setButtonsState();
    }//GEN-LAST:event_onPasswordFieldChange

    private void onHomeFolderChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onHomeFolderChange
        isHomeFolderComplete = lblHomeFolder.getText().length() > 0;
        setButtonsState();
    }
    public Project getProject() {
        return curProject;
    }
    private void setButtonsState() {
        isTestabale = isBaseUrlComplete & isUserNameComplete & isUserFieldComplete & isPasswordComplete & isPasswordFieldComplete;
        isInputComplete = isTestabale & isHomeFolderComplete;
        btnTestConnection.enableInputMethods(isTestabale);
        btnCreate.enableInputMethods(isInputComplete);
    }//GEN-LAST:event_onHomeFolderChange

    private void txtBaseUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseUrlActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSelectHome;
    private javax.swing.JButton btnTestConnection;
    private javax.swing.JComboBox cmbMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBaseUrl;
    private javax.swing.JLabel lblCookie;
    private javax.swing.JLabel lblHomeFolder;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMethod;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordField;
    private javax.swing.JLabel lblSelector;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserField;
    private javax.swing.JTextField txtBaseUrl;
    private javax.swing.JTextField txtCookie;
    private javax.swing.JFormattedTextField txtLoginFormURL;
    private javax.swing.JTextField txtLogout;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPasswordField;
    private javax.swing.JTextField txtSelector;
    private javax.swing.JTextField txtUserField;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

   
}
